#!/bin/bash

# The MIT License (MIT)
#
# Copyright (c) 2015 StarBrilliant <m13253@hotmail.com>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

set -e

print_help() {
    cat<<EOM
Usage: Interactive mode: $0 host-triple
       Batch mode:       $0 host-triple [command]

EOM
    exit
}

main() {
    TRIPLE=
    if [ "$#" -ge 1 ]
    then
        if [ -n "$1" -a "$1" != '--help' ]
        then
            HOST="$1"
            TRIPLE="$1"-
        else
            print_help
        fi
        shift
        if [ "$#" -ne 0 ]
        then
            CHILD_CMD=("$@")
        else
            CHILD_CMD=("${SHELL:-bash}" -i)
        fi
    else
        print_help
    fi
    TEMPDIR="$(mktemp -d --tmpdir crosswrapper.XXXXXXXXXX)"
    [ -z "$TEMPDIR" ] && exit 2
    QUOTE_PATH="$(printf %q "$PATH")"
    IFS=: read -a PATH_ARRAY <<<"$PATH"
    FOUND=
    while IFS= read -d '' COMMAND
    do
        COMMAND_FILENAME="$(basename -- "$COMMAND")"
        if [ "${COMMAND_FILENAME:0:${#TRIPLE}}" = "$TRIPLE" ]
        then
            COMMAND_FILENAME="${COMMAND_FILENAME:${#TRIPLE}}"
            if [ ! -e "$TEMPDIR/$COMMAND_FILENAME" ]
            then
                QUOTE_COMMAND="$(printf %q "$COMMAND")"
                cat >"$TEMPDIR/$COMMAND_FILENAME" <<EOM
#!/bin/bash

PATH=$QUOTE_PATH exec -- $QUOTE_COMMAND "\$@"
EOM
                chmod +x "$TEMPDIR/$COMMAND_FILENAME"
                FOUND=1
                echo "Created \"$COMMAND_FILENAME\""$'\t'"=> \"$COMMAND\"" >&2
            fi
        fi
    done < <(find -L "${PATH_ARRAY[@]}" -maxdepth 1 -type f -executable -print0)
    if [ -z "$FOUND" ]
    then
        rm -rf "$TEMPDIR"
        echo "Found nothing starting with \"$TRIPLE\". Did you typed wrong host-triple?" >&2
        exit 2
    fi
    if [ "$#" -eq 0 ]
    then
        echo "Starting \"${CHILD_CMD[0]}\" shell, type \"exit\" when you finish." >&2
    fi
    PATH="$TEMPDIR:$PATH" "${CHILD_CMD[@]}"
    rm -rfv "$TEMPDIR"
}

main "$@"
